spring.application.name=backend
server.port=8080

# Database Configuration
spring.data.mongodb.uri=mongodb+srv://credit_card_fraud_detection:mypassword@cluster0.ye34fu7.mongodb.net/fraud_detection?appName=Cluster0

# JWT Configuration
app.jwtSecret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwtExpirationMs=86400000

# ML Service URL
app.mlServiceUrl=http://localhost:5000/predict

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
